# Generated by Django 3.2.3 on 2024-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='score',
            new_name='negative',
        ),
        migrations.AddField(
            model_name='chat',
            name='neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chat',
            name='positive',
            field=models.FloatField(default=0.0),
        ),
    ]
